# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 自动健康打卡

on:
  schedule:
    # 此处为UTC时间17点和0点整，对应北京时间+8为1点和8点整
    - cron: 0 17 * * *
    - cron: 0 0 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SCKEY: ${{ secrets.SCKEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pycryptodome

    - name: 自动打卡
      run: |
        python checkin.py
