# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 自动健康打卡

env:
  TZ: Asia/Shanghai
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SCKEY: ${{ secrets.SCKEY }}

on:
  schedule:
    - cron: 4 1 * * *
    - cron: 4 8 * * *
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pycryptodome

    - name: 自动打卡
      run: |
        python checkin.py
